### PR TITLE
Initial hsv implementation

### PR DESCRIPTION
**Pull request by david-sawatzke**
Should we move the `Hsv` struct into the traits crate? Should we add an iterator based conversation (Not sure if it's fast enough)?

This is mostly a port of the fast-led code, of the spectrum variant https://github.com/FastLED/FastLED/wiki/FastLED-HSV-Colors.

### CODE REVIEW

**Comment by sajattack** [comment]
I think this is a good spot for it.

**Comment by sajattack** [comment]
Sorry to nitpick but you misspelled protocol in the README.

**Comment by david-sawatzke** [comment]
Good catch

**Comment by sajattack** [comment]
LGTM

**Pull request merged**
